from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any

class ChatMessage(BaseModel):
    role: str = Field(..., description="user or assistant")
    content: str

class ChatRequest(BaseModel):
    query: str
    session_id: str
    history: List[ChatMessage] = []
    latitude: Optional[float] = None
    longitude: Optional[float] = None

class ChatResponse(BaseModel):
    text: str = Field(..., description="Conversational text response generated by Sarvam AI")
    voice_audio_base64: Optional[str] = Field(None, description="Base64 encoded speech audio from Sarvam TTS (wav/mp3)")
    intent: str = Field(..., description="Classified intent (travel, merchant, support, general)")
    structured_data: Optional[Dict[str, Any]] = Field(None, description="Raw structured search response matching the models (TravelSearchResponse, MerchantSearchResponse, SupportSearchResponse)")
